### ISSUE TITLE
Prepare demonstration

### ISSUE THREAD

**Issue by mwl** [mesos/elasticsearch#36]
List of current issues

- [x] Fix IndexCreationException https://github.com/mesos/elasticsearch/issues/39 @frankscholten
- [ ] Only 2 out of 3 nodes is starting https://github.com/mesos/elasticsearch/issues/37 @frankscholten
- [ ] Setup BigDesk @mrmrcoleman 
- [x] Add example data #38 @mwl
